### ISSUE TITLE
🗺 Maps integration improvements

### ISSUE THREAD

**Issue by bogdan-calapod** [BimmerGestalt/AAIdrive#245] opened 2021-04-08 06:13 UTC
After a talk with @hufman, we determined that the following tasks would improve the UX of the Google Maps integration, and they also seem easy enough to do. I'm opening this issue to track progress on these.

- [x] 🗺 Show location info in advanced settings (`CDS.NAVIGATION.GPSPOSITION` and `CDS.NAVIGATION.GPSEXTENDEDINFO`)
- [x] 📌 Related to #48  - as we figured out that even cars without navi provide GPS info, make the GMapController accept a LocationProvider which pulls data from the car, with a fallback to phone GPS if it fails
- [ ] 👀  Add a wakelock when using Phone GPS to keep updating the location even when the screen is off
- [ ] 🎫 Add next direction info somewhere in the map screen (the Maps API provides this for us, it's just a matter of drawing it on the map somehow)

**Comment by DominikS66** [comment] 2021-04-12 08:56
>     * [ ]  👀  Add a wakelock when using Phone GPS to keep updating the location even when the screen is off
I've tested the GMaps integration on my ID6 during driving while phone screen is off. GPS position is correct updated while driving and map is moved (panning) with centralized GPS position, but map content is not reloaded/updated to actual resolution when driving to "next map sector". Background refresh doesn't seem to work correct. I'll make a video from this issue.

**Comment by flix-one** [comment] 2021-05-01 06:33
First of all, thank you for your extensive work on this project! I was able to create the app with dirtygmap and it's working very well! I like the idea of showing the next direction and was also thinking about another improvement. As I'm using Google Maps for my daily commute to the office, it would be great if there was a menu with "last destinations", where it keeps the last entries I've entered in AAIdrive (e.g. last 20 entries). Just like the standard BMW Navi.

Would that be possible to implement?

**Comment by franmr1979** [comment] 2021-09-09 02:44
Hi, I have the API Key to integrate Gmaps in the app but I can't build the APK, there's always a problem on Android Studio. Could you make a quick video?

**Comment by djenson2000** [comment] 2021-09-09 22:30
> Hi, I have the API Key to integrate Gmaps in the app but I can't build the APK, there's always a problem on Android Studio. Could you make a quick video?

I have the exact same issue, I have downloaded all required apps
here is error file `A problem occurred evaluating root project 'AndroidAutoIdrive'.
Could not find method a() for arguments [build_dbx4h6sgshxk4p13dobvtw2sa$_run_closure1@71c0c2e9] on root project 'AndroidAutoIdrive' of type org.gradle.api.Project.`

There's then a load of expectations.

**Comment by hufman** [comment] 2021-09-09 23:01
That's a very curious error! It is also ridiculously hard to Google for haha.
Do you see the error about the unsupported `distributionSha256Sum` clause in the gradle-wrapper.properties file? I think that line isn't actually doing anything anymore, because I went with using a different verification step, but try disabling that line? What error do you see @franmr1979, send a screenshot or something.
I plan on breaking the Development guide from the Readme out to a full page with screenshots :+1:

**Comment by franmr1979** [comment] 2021-09-10 07:33
I received the error  distributionSha256Sum, tried to disable it but
still can´t build it. I think some screenshots or a little video would
be really useful.
Thank you!


El vie, 10 sept 2021 a las 1:01, Walter Huf
***@***.***>) escribió:
>
> That's a very curious error! It is also ridiculously hard to Google for haha.
> Do you see the error about the unsupported distributionSha256Sum clause in the gradle-wrapper.properties file? I think that line isn't actually doing anything anymore, because I went with using a different verification step, but try disabling that line? What error do you see @franmr1979, send a screenshot or something.
> I plan on breaking the Development guide from the Readme out to a full page with screenshots 👍
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.



-- 
Fran

**Comment by djenson2000** [comment] 2021-09-10 17:25
> That's a very curious error! It is also ridiculously hard to Google for haha.
> Do you see the error about the unsupported `distributionSha256Sum` clause in the gradle-wrapper.properties file? I think that line isn't actually doing anything anymore, because I went with using a different verification step, but try disabling that line? What error do you see @franmr1979, send a screenshot or something.
> I plan on breaking the Development guide from the Readme out to a full page with screenshots 👍

I tried doing this a long time ago. My experience with android studio is just this application, so I'm not familiar with it. the only issue i saw was the version of kotlin being used. I tried putting the kotlin version back down, but still had the error. I just downloaded the latest version of the AAI as its now called, threw the application in the folder and am now getting "06:12 pm	Gradle sync failed: Sync failed: reason unknown (4 m 45 s 759 ms)"

the log file shows this:

"2021-09-10 18:19:19,114 [ 820445]  ERROR - intellij.openapi.progress.Task - Module: 'IDriveConnectKitAndroid' platform 'android-26' not found. 
com.android.tools.idea.gradle.project.sync.idea.issues.SdkPlatformNotFoundException: Module: 'IDriveConnectKitAndroid' platform 'android-26' not found.
	at com.android.tools.idea.gradle.project.sync.idea.SdkSyncUtil.computeSdkReloadingAsNeeded(SdkSyncUtil.kt:127)
	at com.android.tools.idea.projectsystem.gradle.sync.AndroidModuleDataService.postProcess(AndroidModuleDataService.kt:139)
	at com.intellij.openapi.externalSystem.service.project.manage.ProjectDataManagerImpl.lambda$doImportData$1(ProjectDataManagerImpl.java:277)
	at com.intellij.openapi.externalSystem.service.project.manage.ProjectDataManagerImpl.importData(ProjectDataManagerImpl.java:127)
	at com.intellij.openapi.externalSystem.service.project.manage.ProjectDataManagerImpl.importData(ProjectDataManagerImpl.java:207)
	at com.intellij.openapi.externalSystem.service.project.manage.ProjectDataManagerImpl.importData(ProjectDataManagerImpl.java:214)
	at com.android.tools.idea.gradle.project.sync.idea.IdeaSyncPopulateProjectTask.populateProject(IdeaSyncPopulateProjectTask.java:53)
	at com.android.tools.idea.gradle.project.sync.idea.ProjectSetUpTask.doPopulateProject(ProjectSetUpTask.java:54)
	at com.android.tools.idea.gradle.project.sync.idea.ProjectSetUpTask.onSuccess(ProjectSetUpTask.java:48)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$2.handExecutionResult(ExternalSystemUtil.java:546)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$2.executeImpl(ExternalSystemUtil.java:526)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$2.lambda$execute$1(ExternalSystemUtil.java:372)
	at com.intellij.openapi.project.DumbServiceHeavyActivities.suspendIndexingAndRun(DumbServiceHeavyActivities.java:20)
	at com.intellij.openapi.project.DumbServiceImpl.suspendIndexingAndRun(DumbServiceImpl.java:153)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$2.execute(ExternalSystemUtil.java:372)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$4.run(ExternalSystemUtil.java:631)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:935)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$null$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-09-10 18:19:19,115 [ 820446]  ERROR - intellij.openapi.progress.Task - Android Studio 4.2  Build #AI-202.7660.26.42.7322048 
2021-09-10 18:19:19,115 [ 820446]  ERROR - intellij.openapi.progress.Task - JDK: 11.0.8; VM: OpenJDK 64-Bit Server VM; Vendor: N/A 
2021-09-10 18:19:19,115 [ 820446]  ERROR - intellij.openapi.progress.Task - OS: Windows 10 
2021-09-10 18:19:19,115 [ 820446]  ERROR - intellij.openapi.progress.Task - Last Action: EditorLeft "

**Comment by hufman** [comment] 2021-09-10 18:18
That error is indicating that the `IDriveConnectKitAndroid` module is missing, which might be related to how the source code was downloaded. AAIdrive currently uses Git Submodules to include the IDriveConnectKit and IDriveConnectKitAndroid dependencies. If you download the zip of the source code, these modules are not included, nor does it include the `.git` metadata directory. You would need to `git clone --recursive` the repo to download the source code including the submodules.

Since you have Android Studio installed, you should use the `File > New > Project From Version Control` menu item to download the project, which will automatically download the submodules too. This additionally allows for easy updates to the latest version, with the `VCS > Update Project` menu.

**Comment by djenson2000** [comment] 2021-09-11 12:20
![image](https://user-images.githubusercontent.com/86269857/132947205-5553bbf5-2cbb-4ffa-8ca7-c0c4481b3509.png)
This is how I get it. I'm doing it again, one last time in hope it will work 
![image](https://user-images.githubusercontent.com/86269857/132947234-a5b7d69d-258f-4f41-a1e6-8415229a8774.png)
Got this error that you mentioned earlier, removed it as you say to do.
![image](https://user-images.githubusercontent.com/86269857/132947358-b88ccabf-8f48-480d-8282-04c45a8caabb.png)
After that's sorted and I can access the files, thrown the apps in
![image](https://user-images.githubusercontent.com/86269857/132947452-517606e9-7aad-4815-9dcf-7bdd0fdd0bcf.png)
Put a API in with the following permission.
![image](https://user-images.githubusercontent.com/86269857/132947517-4df87de3-b43e-42bd-931b-d0bff01abb25.png)
Started this sync again
![image](https://user-images.githubusercontent.com/86269857/132947537-71897213-a14f-402b-b18c-83f93699f186.png)
And yet again it does this, with the same error I had pointed to previously in logs.

Where am I going wrong??

**Comment by hufman** [comment] 2021-09-11 15:45
Thank you for your patience, and for teaching me what information I will need to show in the planned Developer Guide page!

The steps you show that you did look correct. I was able to reproduce the `Could not find method a() for arguments [..run_closure1] on root project` error by adding an error to the top-level build.gradle file, just a simple `a{}` somewhere in the file or by replacing the `allprojects` with an `a` for example. If this is indeed the same error you are seeing, does `git diff` show anything changed in this file?
The only thing that should show up in `git diff` is the `gradle-wrapper.properties` and _maybe_ the `gradle.properties`, unless you added the properties to your global `~/.gradle/gradle.properties` file. It is definitely meant to build successfully without editing any files (even the CI process only passes environment variables, after decrypting the release key). Does gradle sync properly after you place the external files but before you add the API keys?

I just removed that `distributionSha256Sum` line, so your next pull (after a `git reset --hard` to prevent conflicts (but remember to save your API key ready to put back)) should fix that complaint.

**Comment by djenson2000** [comment] 2021-09-11 16:51
Welp i had just written my results of you request but then my computer really didn't like trying to clone the repository for a 5th time and decided a bluescreen was in order  

Here is my git diff result for that: 
![image](https://user-images.githubusercontent.com/86269857/132955086-39de1f9f-b3ac-4a1c-a35c-bdd81c5996e8.png)

Before the blue screen a few things happen but Tl:dr i totally messed it up and decided to get yet another clone of the repository

This fresh one, with only the apk's and no API failed the gradle sync

you can see I didn't change anything 
![image](https://user-images.githubusercontent.com/86269857/132955241-cab8426e-c936-403c-b811-afeff85d9869.png)

so are my apk's messed up? there the same ones that you linked:
![image](https://user-images.githubusercontent.com/86269857/132955270-9ae89e8a-1afb-4d3f-b054-f165d63f6519.png)

Is there any new ones i can try?

**Comment by hufman** [comment] 2021-09-11 18:30
Hmmm nope, that looks right, and other people have used the same links and same APKs without experiencing this error. The only validity checks that the Gradle script will do is to extract the required files to `app/assets/carapplications`, and it would show a different error message if this had failed, pointing out which specific files were missing.

Can you email me the results of `gradlew assembleGmapNonalyticsDebug --debug > gradle.log`? It would also be interesting to see if the direct Gradle invocation behaves differently than the IDE integration. I'm using Android Studio 4.2.2, if that is a relevant data point to check.

But as this issue is a feature request tracking ticket, I'd like to take build errors to an offline discussion or a separate issue.

**Comment by hufman** [comment] 2021-09-12 16:27
It turned out to be that JAVA_HOME was directing Android Studio to use a JRE instead of its included JDK, and that the Android 26 SDK was not installed. @franmr1979  Please check that the SDK is set up properly:
![image](https://user-images.githubusercontent.com/1592375/132995294-268f85a1-c8e6-48f4-b648-8fa6e27412de.png)

**Comment by hufman** [comment] 2021-09-14 02:58
@franmr1979 Build instructions have been posted to https://bimmergestalt.github.io/AAIdrive/developers hopefully that helps!

**Comment by franmr1979** [comment] 2021-09-14 08:40
Thank you! I have just built the APK! It's working really great.

**Comment by hufman** [comment] 2021-09-25 17:34
@bogdan-calapod  I wonder if your symptom of not receiving location updates might be related to the new `foregroundServiceType` attribute added in Android 10: I [read](https://medium.com/@debuggingisfun/android-foregroundservicetype-8857a36f36b9) that the location provider will only provide updates while the app activity is in the foreground, or if the foreground service has the appropriate `location` attribute, [depending](https://proandroiddev.com/android-q-privacy-changes-for-accessing-device-location-1c8e2197d0e2) on whether the user grants location permission While In Use or All The Time. Perhaps you are experiencing this behavior because you (correctly) only granted location updates While In Use at some point.

Can you try adding `android:foregroundServiceType="location|connectedDevice"` to the MainService definition in AndroidManifest.xml? That might resolve it for you!

**Comment by hufman** [comment] 2022-02-24 15:50
I'm splitting the Next Turn request to a separate issue: #539 
It's very hard, so I'm deferring it from this release.

**Comment by hufman** [comment] 2022-02-24 15:51
I believe the wakelock issue is resolved by having added the foregroundServiceType and also by preferentially using the car's location.

**Closed by hufman** 2022-02-24 15:51 UTC
