### ISSUE TITLE
SOLVED / MyBMW 2.11.1 and wireless communication broken (ID5)

### ISSUE THREAD

**Issue by Nathanpaternotte** [BimmerGestalt/AAIdrive#638] opened 2022-12-01 12:04 UTC
Hello everyone,

I am reporting a problem on ID5 business (end of 2017) with the latest MyBMW 2.11.1 update. Since this update, I have some problems with AAIdrive. I have lost the ability to use the wireless connection (forced to switch to USB) and I have big bugs on Spotify.

Also, in the phone manager on the car, the "Application" box does not appear anymore. A simple downgrade of MyBMW allowed me to get everything working again. I don't know if it's a compatibility issue on AAIDrive or a deletion of this function in the MyBMW application.

Best regards,

Nathan.

**Comment by hufman** [comment] 2022-12-01 17:04
I have not experienced this, my car is working fine with MINI 2.11.1. Is the Apps checkbox actually missing from the phone's options, underneath Phone and Media? The version of MyBMW should not affect this, that's controlled by the ConnectedDrive subscription.
What does MyBMW think about the Apps and subscription status? AAIdrive has little control over whether MyBMW establishes the Apps connection to the car.

**Comment by PiSchleuder** [comment] 2022-12-02 11:28
Hello, 

i have the same problem here using the newest version (latest build) of AADrive with the new MyBMW 2.11.1.

Before updating everything worked via bluetooth - but now i do not get any connection to AADrive again.

best regards

**Comment by marcelleswallace** [comment] 2022-12-02 20:41
Hello,

Same problem with MyBMW 2.11.1 

Any solutions except downgrading the MyBMW app?

**Comment by Stjep10** [comment] 2022-12-02 23:32
Same problem 2.11.1 myBMW

**Comment by ogakul** [comment] 2022-12-03 15:38
Same here, but I could fix it temporarly by disconnecting the phone from the car, open My BMW and confirm all agreements, then reconnect phone (initiated by car). It took a bit longer than usual but worked. But next time I had to reconnect the phone again manually.

**Comment by hufman** [comment] 2022-12-05 18:11
I think I might have an idea about this. The Google Play Store started requiring that apps be compiled for Android 12 as of November, coincidentally when [MyBMW 2.11.0 and 2.11.1 were released](https://apkpure.com/my-bmw/de.bmw.connected.mobile20.na/versions). One of the changes in Android 12 was to require an extra permission to start the app in response to Bluetooth connections, which AAIdrive [has implemented](https://github.com/BimmerGestalt/AAIdrive/commit/068940cc4cbb8fbdc4068a1746b505dbbe0ea163). My personal Android 10 device hasn't noticed any change in behavior :)

I don't have an Android 12+ device, and MyBMW declines to be installed in an emulator, so I can't check to be certain. Try going into the app permissions for MyBMW and checking for a Local Devices permission and manually granting it. If there isn't a Local Devices permission option, then MyBMW hasn't implemented the new method of starting automatically, and you'll have to downgrade to an older MyBMW version or manually open it each time.

![photo1670263524](https://user-images.githubusercontent.com/1592375/205710432-334068eb-93d5-4f88-a5b0-4a320155d45c.jpeg)

**Comment by Toskilabis** [comment] 2022-12-05 18:23
Confirmed that it is a problem of version 2.11.1 of the My BMW app. I have reinstalled version 2.9.1, which you have at the following link, and everything is back to normal.

https://apkfun.com/es/down_My-BMW.40652332.html

**Comment by bogdan-calapod** [comment] 2022-12-06 04:14
@hufman I remember being asked for the local devices permission a couple days back for MyBMW (probably when it updated to 2.11.1) - I think that might be the underlying issue here

**Comment by fookyuanloh** [comment] 2022-12-08 15:55
Same scenario
ID5 (ID6L) with MyBMW 2.11.1 & most recent AAIdrive, unable to connect or load apps
Removed + reinstall both MyBMW & aaidrive

Removed and repair bluetooth between car and phone
Still can't get this to work
Don't see the 'app' checkbox for the connected phone on idrive

I have unlimited connecteddrive subscription
Did a manual download/update of bmw services from idrive

All didn't help
Now I can't even get it to work using USB cable, which makes it worse

**Comment by Toskilabis** [comment] 2022-12-08 16:46
> Confirmed that it is a problem of version 2.11.1 of the My BMW app. I have reinstalled version 2.9.1, which you have at the following link, and everything is back to normal.
> 
> https://apkfun.com/es/down_My-BMW.40652332.html

Has this really worked for anyone? I continue as always with this version and I have canceled the automatic updates of the app in the play store. I don't intend to upgrade until these issues are fixe

**Comment by PiSchleuder** [comment] 2022-12-09 05:13
yes, you have to deinstall the 2.11.1 version und take the old one 2.9.1

**Comment by PiSchleuder** [comment] 2022-12-09 06:22
maybe you have to switch on "install from unknown sources" in android

**Comment by fookyuanloh** [comment] 2022-12-09 07:27
No sir
Wouldn't work

The security policy denies that to be changed

**Comment by hufman** [comment] 2022-12-09 16:07
Have you tried manually granting the Nearby Devices permission to MyBMW? Or as [Bogdan said](https://github.com/BimmerGestalt/AAIdrive/issues/638#issuecomment-1338720562), reinstalling it should show that permission prompt during the initial setup.

**Comment by fookyuanloh** [comment] 2022-12-10 01:08
What have been done so far 
1. Reinstall both MyBMW and aaidrive
2. Permission on nearby device = all enabled
3. Manually update car services
4. Delete bluetooth device on car and phone
5. Re-pair using phone option on car
6. Re-pair using app option - this take massively long and stop (normal?) 

All didn't work to connect wirelessly
However good news is via USB works now

Why not wireless that is the mystery

**Comment by Aro320x** [comment] 2022-12-24 13:38
> Bestätigt, dass es sich um ein Problem der Version 2.11.1 der My BMW App handelt. Ich habe Version 2.9.1 neu installiert, die Sie unter folgendem Link haben, und alles ist wieder normal.
> 
> https://apkfun.com/es/down_My-BMW.40652332.html

I can only confirm!
After updating the My BMW app, no more app connection via Bluetooth.
Have tried many things.
The only thing that worked is to reinstall version 2.9.1. Thus, everything works normally again, as before!

**Comment by hufman** [comment] 2022-12-24 17:40
I just got a new phone for the holidays, and installed version 2.12 from the store, and it seems to work fine for me (even faster and more reliably than my previous phone)! I checked the Permissions and it does have the Nearby Devices permission, please all of you check the permissions. Perhaps upgrading the app missed the step to grant the permission, while uninstalling and installing fresh properly requests the permission.

**Comment by fookyuanloh** [comment] 2022-12-25 02:41
Yes, nearby devices permission enabled
Still can't connect

**Comment by Paolo7297** [comment] 2022-12-25 15:38
Some days ago i installed the updated version (2.12.0) from play store and updated my phone to Android 13, then it started working again.
No hard reset, no data cleared, nothing. Maybe the android version is the key?

**Comment by Aro320x** [comment] 2022-12-26 17:01
Hmm... Glaub nicht dass es an der Android Version liegt!
Ich hab schon länger die Version 13 und bei mir funktioniert es nicht!

**Comment by mauriziopiraccini** [comment] 2022-12-31 17:27
I've got the same problem, BMW G31 2018, ID6, Android 12, app not connecting with MyBMW 2.11 or 2.12, it works fine with version 2.9.3.

**Comment by wiross** [comment] 2023-01-04 16:10
Hello,
BMW F48, ID6, I also have the same problem of not connecting the app:

1. old device with Android 11, MyBMW 2.12.0, AAI 1.2.2 works perfectly 
2. new device with Android 12 and MyBMW2.12.0 AAI 1.2.2 with BT does not connect, 
3. new device with Android 12 and MyBMW2.12.0 AAI 1.4-18 with BT does not connect, 
4. new device with Android 12 and MyBMW2.12.0 AAI 1.4-18 with USB cable works perfectly.
During the BT connection phase, the check does not appear on the IDRIVE APP box, the indicator continues to rotate, and is activated only the phone's BT connection.

**Comment by mauriziopiraccini** [comment] 2023-01-12 17:19
The new MyBMW app version 2.12.2, doesn't seems to solve the problem!

**Comment by hufman** [comment] 2023-01-12 18:24
Thanks for checking! I wish I could reproduce this problem, and then I could dig deeper and help them fix it!

**Comment by wiross** [comment] 2023-01-13 14:19
> new device with Android 12 and MyBMW2.12.0 AAI 1.4-18 with BT does not connect,
Here two screenshot about above: [https://imgur.com/delete/XeGpVwCHRrkmTPY](url)
[https://imgur.com/delete/NuSR8tXzi8TZ3rR](url)

During the phone pair via BT into the car, here the screenshot about ID6: [https://imgur.com/delete/NsB9bCVHqZHjZZz](url)
and here [https://imgur.com/delete/noqvJ938Vrv7J6o](url)
Rotating indicator turn endless, but only phone is connected via BT.

Many thanks for your effort !!

**Comment by mauriziopiraccini** [comment] 2023-01-13 16:00
> > new device with Android 12 and MyBMW2.12.0 AAI 1.4-18 with BT does not connect,
> > Here two screenshot about above: [https://imgur.com/delete/XeGpVwCHRrkmTPY](url)
> > [https://imgur.com/delete/NuSR8tXzi8TZ3rR](url)
> 
> During the phone pair via BT into the car, here the screenshot about ID6: [https://imgur.com/delete/NsB9bCVHqZHjZZz](url) and here [https://imgur.com/delete/noqvJ938Vrv7J6o](url) Rotating indicator turn endless, but only phone is connected via BT.
> 
> Many thanks for your effort !!

Unfortunately the problem is generated by the MyBmw app, starting with the version 2.11.
AAidrive developers can't solve it.
I suggest to write to BMW App support, as I've done some days ago.

**Comment by hufman** [comment] 2023-01-13 16:30
Unfortunately you posted the imgur delete links, so the screenshots are unavailable. But yes, there isn't much AAIdrive can do to help.

**Comment by wiross** [comment] 2023-01-13 19:47
I'm sorry for the wrong links: I add below the correct.
BT pairing with ID6 [https://i.imgur.com/zXQki9q.jpg](url) [https://i.imgur.com/c5C9nlV.jpg](url)

Android 12 with MyBMW2.12.0 and AAI 1.4-18: [https://i.imgur.com/utvAqR5.jpg](url)[https://i.imgur.com/igDbRiz.jpg](url)
Thanks in advance for your attention

**Comment by wiross** [comment] 2023-01-13 19:52
I'm sorry for the wrong links: I add below the correct.
BT pairing with ID6 

![ID6 non si connette](https://user-images.githubusercontent.com/20153919/212406662-5f840c29-2555-480f-825f-838960c8c62a.jpg)
![ID6 settaggio BT telefono](https://user-images.githubusercontent.com/20153919/212406733-84b21705-d946-446e-802f-b8c2d6c4280f.jpg)

Android 12 with MyBMW2.12.0 and AAI 1.4-18: 

![AAI non si connette](https://user-images.githubusercontent.com/20153919/212406851-e778e758-a0b8-46e6-a04a-d0835c910d6a.jpg)
![AAI non connessa](https://user-images.githubusercontent.com/20153919/212406869-48eff01d-4a66-4792-b759-0364d23ebb18.jpg)

Thanks in advance for your attention

**Comment by wiross** [comment] 2023-01-15 16:51
> Unfortunately you posted the imgur delete links, so the screenshots are unavailable. But yes, there isn't much AAIdrive can do to help.

Yesterday I tried again: I reset the ConnectDrive's User and Password into my ID6 on the car, and redone the BT pairing connection with the cell phone, but without success: MyBMW works and connects via BT but not AAI.
![MyBMW connessa AAI non connessa](https://user-images.githubusercontent.com/20153919/212554462-ce813d3b-3917-447c-b62c-0e3337229010.jpg)

**Comment by mauriziopiraccini** [comment] 2023-01-15 18:41
If you check on the car, under connected devices, the phone doesn't have the "App" checked.
Without "App" enabled, AAIdrive can't work.
If you install MyBMW version 2.9.3 (you can download it form apkpure old version https://apkpure.com/my-bmw/de.bmw.connected.mobile20.na/versions ) the "App" will connect again and AAIdrive will start working.

> > Unfortunately you posted the imgur delete links, so the screenshots are unavailable. But yes, there isn't much AAIdrive can do to help.
> 
> Yesterday I tried again: I reset the ConnectDrive's User and Password into my ID6 on the car, and redone the BT pairing connection with the cell phone, but without success: MyBMW works and connects via BT but not AAI.

**Comment by wiross** [comment] 2023-01-15 21:28
> If you check on the car, under connected devices, the phone doesn't have the "App" checked. Without "App" enabled, AAIdrive can't work. If you install MyBMW version 2.9.3 APK (you can download it form apkpure old version https://apkpure.com/my-bmw/de.bmw.connected.mobile20.na/versions ) the "App" will connect again and AAIdrive will start working.
> 
I just tried it, installed the APK previous version 2.9.3 but at login there is a US server and does not recognize my BMW ID from Europe

**Comment by Toskilabis** [comment] 2023-01-15 21:42
https://apkfun.com/es/down_My-BMW.40652332.html

**Comment by Nathanpaternotte** [comment] 2023-01-18 10:57
Hi everyone, all is now ok for me with the last MyBMW app version. Works since the upgrade of my MI 11 T PRO under Android 13.

**Comment by Aro320x** [comment] 2023-01-18 12:07
> Hallo zusammen, bei mir ist jetzt mit der letzten MyBMW App Version alles ok. Funktioniert seit dem Upgrade meines MI 11 T PRO unter Android 13.

Hmm...what number has the version then?
And more importantly. What do you have for ne version in the car, ID5... ID6...???

**Comment by Nathanpaternotte** [comment] 2023-01-18 12:08
MyBMW 2.12.3 and ID5 Business.

**Comment by mauriziopiraccini** [comment] 2023-01-19 17:26
> Hi everyone, all is now ok for me with the last MyBMW app version. Works since the upgrade of my MI 11 T PRO under Android 13.

Bluetooth or USB connection?

**Comment by Nathanpaternotte** [comment] 2023-01-19 17:45
> > Hi everyone, all is now ok for me with the last MyBMW app version. Works since the upgrade of my MI 11 T PRO under Android 13.
> 
> Bluetooth or USB connection?

Bluetooth

**Comment by mauriziopiraccini** [comment] 2023-01-19 18:07
> 

So the problem seems to be only with Android 12, Bluetooth and MyBMW app after version 2.9.3

**Comment by Aro320x** [comment] 2023-01-21 11:02
> > 
> 
> Ich habe ein MI 10 Pro mit Android 12 und mit MyBMW 2.12.3 funktioniert die App-Funktion nicht. Das Problem scheint also nur bei Android 12, Bluetooth und MyBMW App nach Version 2.9.3 zu bestehen

I don't think it's because of the Android version.
I have a Redmi Note 10 Pro with Android 13.
There everything worked fine until the update MyBmw app to version 2.11!!!!

Since I have found nothing to get back to version 2.10., I have installed the APK linked here in the forum pre-version 2.9.3.

And since then everything works fine again...!
Have also tried in the meantime MyBMW 2.12.1.
Unfortunately, the same problem! 🙃

**Comment by Aro320x** [comment] 2023-01-21 11:06
I don't think it's because of the Android version.
I have a Redmi Note 10 Pro with Android 13.
There everything worked fine until the update MyBmw app to version 2.11!!!!

Since I have found nothing to get back to version 2.10. I have installed the APK linked here in the forum pre-version 2.9.3.

And since then everything works fine again...!
Have also tried in the meantime MyBMW 2.12.1.
Unfortunately, the same problem! 🙃

**Comment by snowsurfer001** [comment] 2023-01-22 16:30
Been having the same issue for the last couple months with Spotify / Bluetooth connection...

Using Android 13, with MyBMW 2.12.3, ID6, AAIdrive 1.4-18-22633db it is working again.

Only different thing I did was open MyBMW last night before getting in the car and it asked me to confirm Nearby Devices permission again (even though it was already allowed for the app in the settings).

**Comment by hufman** [comment] 2023-01-23 16:43
That's great to hear that it's starting to work for some people! Can you say what versions you were running before that didn't work?

**Comment by Aro320x** [comment] 2023-01-23 16:52
> 
I use AAdrive Build Version: 1.4 03.05.2022 08:24:26
Where can I get the AAIdrive 1.4-18-22633db?

**Comment by hufman** [comment] 2023-01-23 17:05
Version 1.4-18-22633db means it is 18 builds after the 1.4 release, using commit 22633db. Looking through the [commit log](https://github.com/BimmerGestalt/AAIdrive/commits/main) and [comparing versions](https://github.com/BimmerGestalt/AAIdrive/compare/1.4...22633db1) shows what changed since version 1.4 (a few minor crash fixes and scrolling titles in Music). 1.4-18 is the production version in the Google Play Store, while you probably installed the 1.4 version manually via APK.

**Comment by Aro320x** [comment] 2023-01-23 17:15
> Version 1.4-18-22633db bedeutet, dass es 18 Builds nach der Version 1.4 ist und Commit [22633db verwendet](https://github.com/BimmerGestalt/AAIdrive/commit/22633db1666dbfd32559a3117543263fe833cf65) . Ein Blick in das [Commit-Log](https://github.com/BimmerGestalt/AAIdrive/commits/main) und ein [Vergleich der Versionen](https://github.com/BimmerGestalt/AAIdrive/compare/1.4...22633db1) zeigt, was sich seit Version 1.4 geändert hat (ein paar kleinere Crash-Fixes und scrollende Titel in Music). 1.4-18 ist die Produktionsversion im Google Play Store, während Sie die 1.4-Version wahrscheinlich manuell über APK installiert haben.

Oh okay. So I have the latest version.
Yes I installed mine as apk via github.

**Comment by Aro320x** [comment] 2023-01-24 05:22
So, I have now tried again!  MyBMW updated from APK preversion 2.9.3 to 2.12.3.  AAIdrive installed on Play Store version 1.4-18-22633db. Bmw ID6, phone MIUI Global 13.0.16. Stable.
Result... "AAIdrive is waiting for the apps connection to start" 😖
Just doesn't work for me!!!!
What else do you want me to do? 
![Screenshot_2023-01-24-05-30-12-300_me hufman androidautoidrive](https://user-images.githubusercontent.com/121295790/214217838-d7a5d2c6-a32d-4d79-bd94-7d19877b3c0e.jpg)

**Comment by wiross** [comment] 2023-01-28 21:06
Today I update AAIDrive at 1.4.1 from Playstore, and I can confirm all works without problems (Android 13, MIUI 13.2.6, MyBMW 2.12.3 and ID6)

**Comment by hufman** [comment] 2023-01-28 21:12
AAIdrive 1.4.1 is just a stable release of the beta branch from the store, and should not have any changes about the connection. 👍

**Comment by hufman** [comment] 2023-02-05 16:47
What are the common factors between the new MyBMW working and not working? It sounds like it works for some people on Android 13, while Android 12 does not. Is that the main difference? Is there anyone on Android 13 that doesn't have it working, and does it work for anyone on Android 12?

**Comment by fookyuanloh** [comment] 2023-02-06 07:37
Phone: Samsung S20+
Android ver: 13

Car: F30, 2016, ID6
MyBMW: 2.1.3
AAI: 1.4.1

ConnectedApp - I have lifetime subscription
Kept doing the "download/update" subscription - still the same


1. MyBMW app can't even connect using BT - not per what was show on images above
Not sure how to do this - anybody mind to share what is the pre-requisite

My issue I believe lies behind the MyBMW app unable to connect via BT

**Comment by HaivanJV** [comment] 2023-02-06 09:09
Phone: Poco F3
Android ver: 12

Car F48, 2020, ID6
Working MyBMW: 2.9.3
Non working MyBMW: 2.1.X 

I have all the same problems as @fookyuanloh with 2.1.X MyBMW
With 2.9.3 I can connect Apps via bluetooth, however I need to delete and pair again my connection at all times.
It won't even connect normally to telephone/bluetooth otherwise.

With USB every version works perfectly

**Comment by mauriziopiraccini** [comment] 2023-02-06 09:24
Car: G31 2018
NBTevo: ID5_2211-490-2222A Build 13 - Rev: 37edb37 2022-05-25
Phone: Mi 10 Lite 5G
MIUI: 13.0.4
Android: 12 SKQ1.211006.001
AAIdrive: 1.4.1

Working: My BMW: 2.9.3
Not working: My BMW: 2.10.1 -> 2.12.3

**Comment by mauriziopiraccini** [comment] 2023-02-06 09:56
...
> Exactly the same problem as mine! I've already written a few times here. Unfortunately, no one seems to take care of the matter. 🙃

It's a "My BMW" problem, AAIdrive can't do anything about it.
If you remove AAIdrive from the phone, your car still won't be able to activate "App" feature over Bluetooth, when you've MY BMW 2.11.1 or later.

**Comment by fookyuanloh** [comment] 2023-02-06 10:04
> ...
> 
> > Exactly the same problem as mine! I've already written a few times here. Unfortunately, no one seems to take care of the matter. 🙃
> 
> It's a "My BMW" problem, AAIdrive can't do anything about it. If you remove AAIdrive from the phone, your car still won't be able to activate "App" feature over Bluetooth, when you've MY BMW 2.11.1 or later.


That's what I would have suspected
Hence I believe we should look at how we get the MyBMW app connected via BT first, reliably, then attempt AAI

Hence would like to hear some tips and advise on how to get MyBMW to work.

**Comment by Aro320x** [comment] 2023-02-06 15:57
> ...
> 
> > Genau das gleiche Problem wie bei mir! Ich habe hier schon ein paar mal geschrieben. Leider scheint sich niemand um die Angelegenheit zu kümmern.🙃
> 
> Es ist ein "My BMW"-Problem, AAIdrive kann nichts dagegen tun. Wenn Sie AAIdrive vom Telefon entfernen, kann Ihr Auto die „App“-Funktion über Bluetooth immer noch nicht aktivieren, wenn Sie MY BMW 2.11.1 oder höher haben.

https://github.com/BimmerGestalt/AAIdrive/issues/638#issuecomment-1386863536

I don't understand. Why then write here some that it now works for you with the My BMW app...?

**Comment by fookyuanloh** [comment] 2023-02-08 08:45
Good news !!
Managed to get mine working WIRELESSLY !!!

Pre-requisite:
1. Delete BT pair profile on phone
2. Delete mobile device from iDrive
3. On MyBMW app, delete your vehicle from your profile/account
4. Uninstall both MyBMW & AAI from your phone
5. From iDrive, go download/update your ConnectedDrive provisioned info - there is a reddit page by @hufman  on how to do this, to ensure your iDrive has the latest info on what is allocated for you

Next steps:
1. Download/install MyBMW from Google AppStore
2. Login ,and add your vehicle back into the MyBMW app, then keep the MyBMW app running (in the background)
3. Re-pair your phone to the vehicle, on ID5/6 select pair as "App" instead of BT
4. Keep fingers/toe etc crossed 
5. If step 4 works, you should see App checkbox as part option in your Managed Mobile Device (make that is ticked)
6. Download/install AAI = happy days ahead

Note:
Phone: Samsung S20+
Android ver: 13
Car: F30, 2016, ID6
No change on the variables


Shouldn't have any changes - since there were no updates before I uninstall them
I've also checked the version post re-installation
MyBMW: 2.1.3
AAI: 1.4.1

My HU was an upgraded from unit ID4 to ID5 (with ID6 UI - should be ID6 lite?), 
Done this earlier because I wanted WIRELESS AAI, however didn't manage to get it to work back then.

**Comment by HaivanJV** [comment] 2023-02-11 09:39
I want to flag a method that helped me resolving some phone/idrive pairing issues.
I had big improvements by deleting the Bluetooth App cache/data.
https://squareup.com/help/us/en/article/6828-clear-your-android-device-s-bluetooth-cache

These were preventing the phone to automatically connect with the car. A clean slate now made the connection way smoother with MyBmw 2.9.3

It still didn't solve for the newer version of the App instead

**Comment by wiross** [comment] 2023-02-12 21:38
Hallo,
I can confirm that after the main update from Xiaomi13 to Xiaomi14 (14.0.5),  all works without problems !!

**Comment by HaivanJV** [comment] 2023-03-16 05:57
Just received the Android 13 update on my Poco F3.
Also in my case, all is now resolved and the newest version of My BMW works as expected.

**Closed** 2023-07-10 14:32 UTC
